baseURL: "https://erenming.github.io/"
languageCode: "zh"
title: "Erenming's Blog"
theme: "paperMod"

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 5

params:
  ShowCodeCopyButtons: true
  homeInfoParams:
    Title: Hi there 👋
    Content: Keep It Simple Stupid!

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/erenming"
    - name: medium
      url: "https://medium.com/@erenming"
    - name: cnblog
      url: https://www.cnblogs.com/erenming/